#!/bin/sh

# comparing floating point vs fixed point accuracy

gnuplot <<EOF
g(x) = 1.234535 + 0.02229774 * (x + 1.215454) - 0.0002962121 * (x + 1.215454)**2

set terminal png size 1100,600
set output "integer-vs-float.png"
set grid
set xtic rotate by -45 scale 0 nomirror
set ylabel ""
set format x "%1.1f degF"
set ytics format "%1.3f ppm" nomirror
set title "integer vs float"
set key bottom left box
plot \
 "integers.log" using 1:(\$2/1000) title "integer", \
 "floats.log" using 1:2 title "floats", \
 g(x) title "gnuplot"
EOF
